// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2CoKdov0l4b9q_9eim8GjU8iCWDdYOSA',
    appId: '1:172259733368:android:e4b5211b2ff513aaf1e28d',
    messagingSenderId: '172259733368',
    projectId: 'chatappflutter-fbcee',
    storageBucket: 'chatappflutter-fbcee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2CoKdov0l4b9q_9eim8GjU8iCWDdYOSA',
    appId: '1:172259733368:android:e4b5211b2ff513aaf1e28d',
    messagingSenderId: '172259733368',
    projectId: 'chatappflutter-fbcee',
    storageBucket: 'chatappflutter-fbcee.firebasestorage.app',
    androidClientId: '288842837392-gse3j6u9fferoav9leh2ik3468asfeup.apps.googleusercontent.com',
    iosClientId: '288842837392-sgib97u6439i4jte3bo19u00fh663euu.apps.googleusercontent.com',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2CoKdov0l4b9q_9eim8GjU8iCWDdYOSA',
    appId: '1:172259733368:android:e4b5211b2ff513aaf1e28d',
    messagingSenderId: '172259733368',
    projectId: 'chatappflutter-fbcee',
    storageBucket: 'chatappflutter-fbcee.firebasestorage.app',
    authDomain: 'we-chat-75f13.firebaseapp.com',
  );
}